name: Dev Deployment

on:
  pull_request:
    branches:
      - main
    types: [ closed ]



jobs:
  deploy:
    environment: DEV
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v2

      #  Package jar

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true


      # Heroku login
      - name: Heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_APP }}
        run: |
          heroku container:push web -a ${{ secrets.HEROKU_APP }}
          heroku container:release web -a ${{ secrets.HEROKU_APP }}